services:
  quizzle:
    image: germannewsmaker/quizzle:latest
    ports:
      - "6412:6412"
    volumes:
      - quizzle_data:/quizzle/data
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped

volumes:
  quizzle_data:
    name: quizzle_data
